//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderRepository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OrderDBContextContainer : DbContext
    {
        public OrderDBContextContainer()
            : base("name=OrderDBContextContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> CustomerSet { get; set; }
        public virtual DbSet<Order> OrderSet { get; set; }
        public virtual DbSet<OrderLine> OrderLineSet { get; set; }
        public virtual DbSet<CreditCard> CreditCardSet { get; set; }
        public virtual DbSet<category> categorySet { get; set; }
        public virtual DbSet<Item> ItemSet { get; set; }
    }
}
