//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace City_Repository.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DictType
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Remark { get; set; }
        public string Seq { get; set; }
        public string Editor { get; set; }
        public string LastUpdated { get; set; }
        public string PID { get; set; }
    }
}
