//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_批量插入性能对比
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeterResponseSequence
    {
        public int ID { get; set; }
        public int SourceID { get; set; }
        public long DeviceCode { get; set; }
        public int UseID { get; set; }
        public int MeterID { get; set; }
        public int ArrivalsState { get; set; }
        public int ExecState { get; set; }
        public int BusinessState { get; set; }
    }
}
